In [9]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer

In [10]:
df = pd.read_csv("data/final_results.csv")

In [13]:
df.head()

,gemeente,year,is_weekend_ratio,acc_during_is_weekend,total_accidents,total_cycling_accidents,car_conflict,severity,slick,light,...,prev_year_total_cyc_accidents,historical_town_avg,school_zone_exposure,risk_per_1k_residents,weather_severity_index,flow_density,smoothed_target,predicted_num_accidents,pred_per_1k_residents,risk_rank
0,Gent,2025.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,550.0,442.80,6.401417,4.694543,0.604669,0.016337,0.0,568,2.083203,1.0
1,Brugge,2025.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,203.0,164.40,2.874811,4.298197,0.885652,0.033503,0.0,219,1.820706,2.0
2,Leuven,2025.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,208.0,140.00,0.817294,3.488838,0.651850,0.114405,0.0,207,1.973195,3.0
3,Kortrijk,2025.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,122.0,98.60,1.238004,4.159651,0.886546,0.091269,0.0,133,1.646529,4.0
4,Mechelen,2025.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,125.0,79.25,4.801774,3.045006,0.633077,0.025570,0.0,132,1.472311,5.0

In [14]:
df_tiers = df[["gemeente", "predicted_num_accidents", "total_pop"]].copy()

In [15]:
df_tiers["people_that_cycle"] = (1 - 0.29) * df_tiers["total_pop"]
df_tiers["accidents_per_100_cyclists"] = df_tiers["predicted_num_accidents"] / (
    df_tiers["people_that_cycle"] / 100
)

In [16]:
df_tiers["accidents_per_100_cyclists"] = (
    df_tiers["accidents_per_100_cyclists"].fillna(0).replace([np.inf, -np.inf], 0)
)

In [17]:
X = df_tiers[["accidents_per_100_cyclists"]].values

In [18]:
discretizer = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="kmeans", random_state=7)

In [19]:
df_tiers["bin_encoded"] = discretizer.fit_transform(X).astype(int)

In [20]:
color_mapping = {
    0: "Green",
    1: "Yellow",
    2: "Red"
}

In [21]:
df_tiers["risk_tier"] = df_tiers["bin_encoded"].map(color_mapping)

In [22]:
bin_edges = discretizer.bin_edges_[0]
print(f"Green Tier Range:  {bin_edges[0]:.4f} to {bin_edges[1]:.4f}")
print(f"Yellow Tier Range: {bin_edges[1]:.4f} to {bin_edges[2]:.4f}")
print(f"Red Tier Range:    {bin_edges[2]:.4f} to {bin_edges[3]:.4f}\n")

Green Tier Range:  0.0303 to 0.1280
Yellow Tier Range: 0.1280 to 0.2247
Red Tier Range:    0.2247 to 0.3206

In [25]:
print(df_tiers[["gemeente", "accidents_per_100_cyclists", "risk_tier"]].sample(n=5))

        gemeente  accidents_per_100_cyclists risk_tier
26          Zele                    0.255237       Red
60      Kraainem                    0.030311     Green
54  Herk-de-Stad                    0.098059     Green
25        Lommel                    0.156014    Yellow
23          Bree                    0.319172       Red

In [26]:
df_tiers

,gemeente,predicted_num_accidents,total_pop,people_that_cycle,accidents_per_100_cyclists,bin_encoded,risk_tier
0,Gent,568,272657.0,193586.47,0.293409,2,Red
1,Brugge,219,120283.0,85400.93,0.256437,2,Red
2,Leuven,207,104906.0,74483.26,0.277915,2,Red
3,Kortrijk,133,80776.0,57350.96,0.231905,2,Red
4,Mechelen,132,89655.0,63655.05,0.207368,1,Yellow
...,...,...,...,...,...,...,...
57,Sint-Pieters-Leeuw,8,36732.0,26079.72,0.030675,0,Green
58,As,7,8298.0,5891.58,0.118814,0,Green
59,Pepingen,5,4564.0,3240.44,0.154300,1,Yellow
60,Kraainem,3,13940.0,9897.40,0.030311,0,Green
61,Heers,2,7574.0,5377.54,0.037192,0,Green

In [ ]:
df_tiers.to_csv("data/tiers.csv", index=False)

In [31]:
df_tiers[df_tiers["gemeente"] == "Heist-op-den-Berg"]

,gemeente,predicted_num_accidents,total_pop,people_that_cycle,accidents_per_100_cyclists,bin_encoded,risk_tier
24,Heist-op-den-Berg,39,44723.0,31753.33,0.122822,0,Green

In [ ]:
df["severity"]

np.float64(0.0)

In [38]:
df.columns

Index(['gemeente', 'year', 'is_weekend_ratio', 'acc_during_is_weekend',
       'total_accidents', 'total_cycling_accidents', 'car_conflict',
       'severity', 'slick', 'light', 'intersection', 'school_peak',
       'local_accidents', 'total_hourly_flow', 'avg_temp', 'avg_precip',
       'avg_mun_wind', 'bad_weather_ratio', 'relative_sensor_age',
       'avg_income_per_capita', 'prof_earner_ratio', 'avg_employment_rate',
       'inbound_push_ratio', 'total_pop', 'pct_young_children',
       'pct_school_kids', 'pct_uni_students', 'pct_young_profs',
       'pct_senior_profs', 'pct_seniors', 'pct_male', 'pct_female',
       'pct_belgian', 'pct_foreign', 'pct_single', 'pct_married',
       'pct_widowed', 'pct_divorced', 'accident_rate_per_flow',
       'accident_rate_per_capita', 'severity_index', 'prev_year_severe_count',
       'prev_year_dark_count', 'prev_year_weekend_count',
       'prev_year_local_accidents', 'prev_year_school_accidents',
       'prev_year_slick_accidents', 'prev_year_carconflict_accidents',
       'prev_year_int_accidents', 'prev_year_total_accidents',
       'prev_year_total_cyc_accidents', 'historical_town_avg',
       'school_zone_exposure', 'risk_per_1k_residents',
       'weather_severity_index', 'flow_density', 'smoothed_target',
       'predicted_num_accidents', 'pred_per_1k_residents', 'risk_rank'],
      dtype='str')

In [39]:
df[["slick", "light", "intersection"]]

    slick  light  intersection
0     0.0    0.0           0.0
1     0.0    0.0           0.0
2     0.0    0.0           0.0
3     0.0    0.0           0.0
4     0.0    0.0           0.0
..    ...    ...           ...
57    0.0    0.0           0.0
58    0.0    0.0           0.0
59    0.0    0.0           0.0
60    0.0    0.0           0.0
61    0.0    0.0           0.0

[62 rows x 3 columns]

In [40]:
df["slick"].sum()

np.float64(0.0)

In [42]:
df["light"].sum()

np.float64(0.0)

In [43]:
df["intersection"].sum()

np.float64(0.0)